const fs=require('node:fs');const assert=require('node:assert/strict');const {JSDOM}=require('../../frontend/node_modules/jsdom');
const errors=[];const dom=new JSDOM(fs.readFileSync(__dirname+'/cultivo-claro-v2.html','utf8'),{runScripts:'dangerously',beforeParse(w){w.ResizeObserver=class{observe(){}};w.addEventListener('error',e=>errors.push(e.message));}});
const q=s=>dom.window.document.querySelector(s),change=(selector,value)=>{q(selector).value=value;q(selector).dispatchEvent(new dom.window.Event('change'));};
assert.equal(q('#c-review').hidden,false);assert.equal(q('#c-confirm-alert').disabled,true);
change('#c-review-clock','later');
assert.match(q('.c-date strong').textContent,/28 de septiembre/);
assert.equal(q('#c-confirm-alert').disabled,false);
assert.match(q('#c-review-state').textContent,/Pendiente de revisión/);
change('#c-review-clock','review');assert.equal(q('#c-confirm-alert').disabled,false);
assert.match(q('.c-date strong').textContent,/21 de septiembre/);
assert.match(q('#c-review-context').textContent,/Alerta para el 21 de septiembre/);
q('#c-confirm-alert').click();assert.equal(q('#c-review-form').hidden,false);
q('#c-review-cancel').click();assert.match(q('#c-review-state').textContent,/Pendiente/);
q('#c-confirm-alert').click();q('#c-review-note').value='Coincide con lo observado.';
q('#c-review-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
assert.match(q('#c-review-state').textContent,/Alerta confirmada/);assert.match(q('#c-days').textContent,/Revisión: confirmada/);
assert.match(q('#c-review-state').textContent,/Revisión del 21 de septiembre/);
change('#c-sector','sur');assert.equal(q('#c-review').hidden,true);assert.doesNotMatch(q('#c-days').textContent,/confirmada/);
change('#c-sector','norte');assert.match(q('#c-review-state').textContent,/Alerta confirmada/);
q('#c-review-edit').click();q('#c-reject-alert').click();q('#c-review-note').value='No coincidió con la observación.';
q('#c-review-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
assert.match(q('#c-review-state').textContent,/Alerta rechazada/);assert.match(q('#c-days').textContent,/75/);assert.match(q('#c-days').textContent,/Revisión: rechazada/);
assert.equal(q('#c-days').children[2].querySelector('.c-status').textContent,'⚠ Alerta');
q('#c-days').children[0].click();assert.equal(q('#c-review').hidden,true);
q('#c-days').children[2].click();change('#c-review-clock','later');
q('#c-review-edit').click();q('#c-confirm-alert').click();
q('#c-review-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
assert.match(q('#c-review-state').textContent,/Revisión del 28 de septiembre/);
assert.match(q('#c-review-context').textContent,/Alerta para el 21 de septiembre/);
assert.deepEqual(errors,[]);console.log('PASS: fecha futura bloqueada, confirmar, cancelar, rechazar, editar, aislamiento por sector y pronóstico original conservado.');dom.window.close();
